### ISSUE TITLE
`weight` should be `target_weight` in template?

### ISSUE THREAD

**Issue by coolzilj** [wanming/xueqiu_reminder#1]
https://github.com/wanming/xueqiu_reminder/blob/master/config.example.js#L33

![image](https://cloud.githubusercontent.com/assets/1059327/8018796/cd0614d4-0c5f-11e5-83d9-a3f8d8dd45d9.png)

I think `target_weight` is what we want?

**Comment by coolzilj** [comment]
Nevermind, I figure it out. : )

**Comment by wanming** [comment]
Are you sure about that?
